/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Chat_item: typeof import('./../components/custom/chat_item.vue')['default']
    HelloWorld: typeof import('./../components/HelloWorld.vue')['default']
    'IconBx:adjust': typeof import('~icons/bx/adjust')['default']
    'IconMdi:account': typeof import('~icons/mdi/account')['default']
    'IconSolar:accumulatorBoldDuotone': typeof import('~icons/solar/accumulator-bold-duotone')['default']
    'IconSvgSpinners:90Ring': typeof import('~icons/svg-spinners/90-ring')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./../components/custom/svg-icon.vue')['default']
  }
}
